# Generated by Django 2.0.2 on 2018-06-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=30)),
                ('branch_level', models.CharField(choices=[('main', 'Main Branch'), ('other', 'Other Branch')], default='other', max_length=15)),
                ('registration_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_number', models.CharField(max_length=15)),
                ('mobile_number', models.CharField(max_length=15)),
                ('fax_number', models.CharField(max_length=15)),
                ('email_address', models.CharField(max_length=30)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.branch')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=15)),
                ('dep_description', models.TextField(max_length=1024)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.branch')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=15)),
                ('county', models.CharField(max_length=15)),
                ('sub_county', models.CharField(max_length=15)),
                ('parish', models.CharField(max_length=15)),
                ('town', models.CharField(max_length=15)),
                ('zone', models.CharField(max_length=15)),
                ('unique_direction', models.CharField(max_length=15)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.branch')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='service_unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=30)),
                ('unit_innitials', models.CharField(max_length=10)),
                ('unit_type', models.CharField(choices=[('min', 'Ministry'), ('org', 'Organization'), ('firm', 'Firm'), ('other', 'Others')], default='min', max_length=15)),
                ('unit_description', models.TextField(max_length=1024)),
                ('unit_logo', models.CharField(max_length=500)),
                ('unit_featured_image', models.CharField(max_length=500)),
                ('unit_cover_photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'service_unit',
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_first_name', models.CharField(max_length=15)),
                ('staff_last_name', models.CharField(max_length=15)),
                ('staff_contact', models.CharField(max_length=15)),
                ('staff_email_address', models.CharField(max_length=30)),
                ('staff_designation', models.CharField(max_length=30)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.department')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.service_unit'),
        ),
    ]
