# Generated by Django 2.0.2 on 2018-06-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('placement_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('reason', models.TextField(max_length=512)),
                ('appointment_mode', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('settled', 'Settled'), ('select', 'Select Appointment Mode')], default='select', max_length=15)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='avails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availer', models.CharField(max_length=15)),
                ('session_start', models.DateTimeField()),
                ('session_stop', models.DateTimeField()),
            ],
            options={
                'db_table': 'avails',
            },
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=30)),
                ('branch_level', models.CharField(choices=[('main', 'Main Branch'), ('other', 'Other Branch')], default='other', max_length=15)),
                ('registration_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=15)),
                ('client_last_name', models.CharField(max_length=15)),
                ('client_contact', models.CharField(max_length=15)),
                ('location_district', models.CharField(max_length=15)),
                ('location_town', models.CharField(max_length=15)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.appointment')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('office_number', models.CharField(max_length=15)),
                ('fax_number', models.CharField(max_length=15)),
                ('email_address', models.CharField(max_length=15)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.branch')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('department_description', models.TextField(max_length=1024)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.branch')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=15)),
                ('county', models.CharField(max_length=15)),
                ('sub_county', models.CharField(max_length=15)),
                ('parish', models.CharField(max_length=15)),
                ('town', models.CharField(max_length=15)),
                ('zone', models.CharField(max_length=15)),
                ('unique_direction', models.CharField(max_length=15)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.branch')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='service_unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=30)),
                ('unit_type', models.CharField(choices=[('select', 'Select Type of service unit'), ('min', 'Ministry'), ('org', 'Organization'), ('firm', 'Firm'), ('other', 'Others')], default='select', max_length=15)),
                ('unit_description', models.TextField(max_length=1024)),
                ('unit_logo', models.CharField(max_length=500)),
                ('unit_featured_image', models.CharField(max_length=500)),
                ('unit_cover_photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'service_unit',
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('staff_first_name', models.CharField(max_length=15)),
                ('staff_last_name', models.CharField(max_length=15)),
                ('staff_profile_photo', models.CharField(max_length=512)),
                ('staff_designation', models.CharField(choices=[('system_admin', 'System administrator'), ('Official', 'Official'), ('receptionist', 'Receptionist'), ('select', 'Select Staff Designation')], default='select', max_length=15)),
                ('about_staff', models.TextField(max_length=512)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.department')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='system_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.branch')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.staff')),
            ],
            options={
                'db_table': 'system_admin',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, unique=True)),
                ('user_password', models.CharField(max_length=100)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.staff')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.service_unit'),
        ),
        migrations.AddField(
            model_name='avails',
            name='availed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.staff'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.staff'),
        ),
    ]
