# Generated by Django 2.0.2 on 2018-08-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orims', '0003_auto_20180814_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='unit_id',
            new_name='sunit_id',
        ),
    ]
