# Generated by Django 2.0.2 on 2018-09-09 18:13

from django.db import migrations, models
import orims.custom


class Migration(migrations.Migration):

    dependencies = [
        ('orims', '0005_auto_20180814_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceunit',
            name='unit_cover_photo',
            field=models.FileField(max_length=2000, upload_to=orims.custom.RandomFileName('photos/uploads/ServiceUnit/cover_photos')),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='unit_featured_image',
            field=models.FileField(max_length=2000, upload_to=orims.custom.RandomFileName('photos/uploads/ServiceUnit/featured_images')),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='unit_logo',
            field=models.FileField(max_length=2000, upload_to=orims.custom.RandomFileName('photos/uploads/ServiceUnit/logos')),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='unit_type',
            field=models.CharField(choices=[('select', '--Select Category--'), ('Ministry', 'Ministry'), ('Organization', 'Organization'), ('Firm', 'Firm'), ('Other', 'Others')], default='select', max_length=15, verbose_name='Service Unit type'),
        ),
    ]
