# Generated by Django 2.0.2 on 2018-09-19 15:53

from django.db import migrations, models
import orims.custom


class Migration(migrations.Migration):

    dependencies = [
        ('orims', '0006_auto_20180909_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceunit',
            name='unit_cover_photo',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to=orims.custom.RandomFileName('photos/uploads/ServiceUnit/cover_photos')),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='unit_featured_image',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to=orims.custom.RandomFileName('photos/uploads/ServiceUnit/featured_images')),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='unit_logo',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to=orims.custom.RandomFileName('photos/uploads/ServiceUnit/logos')),
        ),
        migrations.AlterField(
            model_name='serviceunit',
            name='unit_name',
            field=models.CharField(max_length=500, verbose_name='Service Unit name'),
        ),
    ]
