# Generated by Django 2.0.2 on 2018-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orims', '0007_auto_20180919_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AddField(
            model_name='department',
            name='registration_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='office',
            name='registration_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceunit',
            name='registration_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='registration_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
