# Generated by Django 2.0.2 on 2018-07-17 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('placement_time', models.DateTimeField(verbose_name='Appointment placement Time')),
                ('start_time', models.DateTimeField(verbose_name='Time when appointment starts')),
                ('stop_time', models.DateTimeField(verbose_name='Time when Appointment ends')),
                ('reason', models.TextField(max_length=512, verbose_name='Reason for appointment schedule')),
                ('appointment_mode', models.CharField(choices=[('pend', 'Pending'), ('canc', 'Canceled'), ('fwd', 'Forwarded'), ('conf', 'Confirmed'), ('setd', 'Settled'), ('non', 'None')], default='non', max_length=15, verbose_name='Current appointment mode')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.Staff', verbose_name='Staff')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Avails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availer', models.CharField(max_length=15)),
                ('session_start', models.DateTimeField()),
                ('session_stop', models.DateTimeField()),
                ('availed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.Staff')),
            ],
            options={
                'db_table': 'Avails',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=15, verbose_name='First Name')),
                ('client_last_name', models.CharField(max_length=15, verbose_name='Last Name')),
                ('client_contact', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('client_location_district', models.CharField(max_length=15, verbose_name='District')),
                ('client_location_town', models.CharField(max_length=15, verbose_name='Town')),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment')),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_date', models.DateField(verbose_name='When Schedule was made')),
                ('effect_date', models.DateField(verbose_name='When Schedule is to effect')),
                ('start_time', models.TimeField(verbose_name='Schedule start time')),
                ('end_time', models.TimeField(verbose_name='Schedule End time')),
                ('sch_reason', models.TextField(max_length=512, verbose_name='Reason for schedule')),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.Staff', verbose_name='Staff')),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
    ]
