# Generated by Django 2.0.2 on 2018-06-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orims', '0002_auto_20180628_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('placement_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('reason', models.TextField(max_length=512)),
                ('appointment_mode', models.CharField(choices=[('pend', 'Pending'), ('canc', 'Canceled'), ('fwd', 'Forwarded'), ('conf', 'Confirmed'), ('setd', 'Settled'), ('non', 'None')], default='non', max_length=15)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.Staff')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=15)),
                ('client_last_name', models.CharField(max_length=15)),
                ('client_contact', models.CharField(max_length=15)),
                ('client_location_district', models.CharField(max_length=15)),
                ('client_location_town', models.CharField(max_length=15)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment')),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_date', models.DateField(max_length=3, verbose_name='Date when Schedule is made')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sch_reason', models.TextField(max_length=512)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.Staff')),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
    ]
