# Generated by Django 2.0.2 on 2018-10-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avails',
            options={'verbose_name_plural': 'Avails'},
        ),
    ]
