# Generated by Django 2.0.2 on 2018-10-07 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20181005_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='placement_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Appointment placement Time'),
        ),
        migrations.AlterField(
            model_name='avails',
            name='session_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sch_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='When Schedule was made'),
        ),
    ]
