# Generated by Django 2.0.2 on 2018-08-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemadmin',
            name='system_admin_email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='system_admin_password',
            field=models.CharField(max_length=500),
        ),
    ]
