# Generated by Django 2.0.2 on 2018-08-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0002_auto_20180814_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemadmin',
            name='system_admin_profile_photo',
            field=models.FileField(default=1, max_length=500, upload_to='photos/uploads/System_Admin/profile_photos'),
            preserve_default=False,
        ),
    ]
