# Generated by Django 2.0.2 on 2018-09-09 18:13

from django.db import migrations, models
import orims.custom


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0003_systemadmin_system_admin_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemadmin',
            name='system_admin_profile_photo',
            field=models.FileField(max_length=500, upload_to=orims.custom.RandomFileName('photos/uploads/System_Admin/profile_photos/')),
        ),
    ]
