# Generated by Django 2.0.2 on 2018-10-18 03:23

from django.db import migrations, models
import django.utils.timezone
import orims.custom


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0004_auto_20180909_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemadmin',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='systemadmin',
            name='system_admin_cover_photo',
            field=models.FileField(default=1, max_length=1024, upload_to=orims.custom.RandomFileName('photos/uploads/System_Admin/cover_photos/')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemadmin',
            name='system_admin_first_name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemadmin',
            name='system_admin_last_name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='system_admin_profile_photo',
            field=models.FileField(max_length=1024, upload_to=orims.custom.RandomFileName('photos/uploads/System_Admin/profile_photos/')),
        ),
    ]
