# Generated by Django 2.0.2 on 2018-10-18 16:03

from django.db import migrations, models
import orims.custom


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0005_auto_20181018_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemadmin',
            name='system_admin_cover_photo',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=orims.custom.RandomFileName('photos/uploads/System_Admin/cover_photos/')),
        ),
        migrations.AlterField(
            model_name='systemadmin',
            name='system_admin_profile_photo',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=orims.custom.RandomFileName('photos/uploads/System_Admin/profile_photos/')),
        ),
    ]
