# Generated by Django 2.0.2 on 2018-06-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orims', '0002_auto_20180628_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, unique=True)),
                ('user_password', models.CharField(max_length=50)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orims.Staff')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
