# Generated by Django 2.0.2 on 2018-10-23 19:49

from django.db import migrations, models
import django.utils.timezone
import orims.custom


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('Receptionist_id', models.AutoField(primary_key=True, serialize=False)),
                ('Receptionist_user_name', models.CharField(max_length=254)),
                ('Receptionist_first_name', models.CharField(max_length=254)),
                ('Receptionist_last_name', models.CharField(max_length=254)),
                ('Receptionist_password', models.CharField(max_length=500)),
                ('Receptionist_email', models.EmailField(max_length=500)),
                ('Receptionist_profile_photo', models.FileField(blank=True, max_length=1024, null=True, upload_to=orims.custom.RandomFileName('photos/uploads/Receptionist/profile_photos/'))),
                ('Receptionist_cover_photo', models.FileField(blank=True, max_length=1024, null=True, upload_to=orims.custom.RandomFileName('photos/uploads/Receptionist/cover_photos/'))),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
